version: '3.9'
services:
    config-server:
        image:  bootcamp2022/config-server
        restart: always
        ports:
            - 9010:9010
  
    eureka-server:
        image:  bootcamp2022/eureka-server
        restart: always
        ports:
            - 8761:8761
        depends_on:
            config-server:
                condition: service_started

    mongodb:
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=bootcamp
            - MONGO_INITDB_ROOT_PASSWORD=secret
            
    ms-customer:
        image:  bootcamp2022/ms-customer
        environment: 
            - MONGODB_CONNSTRING=mongodb://bootcamp:secret@mongodb
        restart: always
        ports:
            - 8081:8081
        depends_on:
            config-server:
                condition: service_started
            eureka-server:
                condition: service_started
            mongodb:
                condition: service_started