server:
  port: 8083
spring:
  data:
    mongodb:
      database: accountdb
      host: localhost
      port: 27017
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include: *
    shutdow:
      enable: true
    health:
      show-details: always
info:
  app:
    name: Spring Boot MS Customer
    web: *
  hello: Hi There

