server:
  port: 8085
spring:
  data:
    mongodb:
      database: paymentdb
      host: localhost
      port: 27017
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh, restart, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true

