application:
  location: config (Github)
  config:
    profile: dev
    description: valor obtenido desde "ms-transaction.yml"
spring:
  data:
    mongodb:
      database: mongodb
      #host: localhost
      host: mongodb
      port: 27017
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka


management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh, restart, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true

  user:
    mzena:
      id: 1000
      name: Manuel
      lastname: Zena
      active: true
    azena:
      id: 1001
      name: Alejandro
      lastname: Zena
      active: true