application:
  location: config (Github)
  config:
    profile: dev
    description: valor obtenido desde "ms-yanki-dev.yml"
spring:
  data:
    mongodb:
      database: mongodb
      #host: localhost
      host: mongodb
      port: 27017
  kafka:
    bootstrap-servers: localhost:29092
    
server:
  port: 8091

eureka:
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka-server:8761/eureka